### ISSUE TITLE
Sabnzbd, Sickbeard SSL issue vs Python 2.7.9

### ISSUE THREAD

**Issue by Eldinnie** [SynoCommunity/spksrc#1575]
Since the last update for Python (2.7.9) is seems SSL, is a lot stricter. 
This is great, except for some sites (like Usnenet-crawler.com) it means RSS can no longer be read due to SSL issues.
Is there a way to fix this?

**Comment by Dr-Bean** [comment]
Caused by Python 2.7.9, and more specifically [PEP476](http://legacy.python.org/dev/peps/pep-0476/) if I'm not mistaken.
Ultimately, this will have to be fixed by either SABnzbd, Sickbeard/rage etc. Make sure you report it to their maintainers if that's not already done.

**Comment by Dr-Bean** [comment]
@Diaoul An alternative course of action might be to give the maintainers of Sab, sick, couch etc the opportunity to get things fixed for Python 2.7.9 within a reasonable timeframe. What do you think?

**Comment by Diaoul** [comment]
So you suggest deactivating the version for now? This will still leave users who updated their python package with the problem.
I think we should follow Python on this and have the applications maintainers update their applications. There are security concerns at stake here.

**Comment by Dr-Bean** [comment]
Well, obviously, but breaking packages for a large number of people isn't a great option either :)

While reading the PEP, this is how I understand it: 
The problem seems to occur because DSM doesn't provide the root certificates (or system-provided certificate database) in a default, reachable location for the software. So, as per the PEP, stuff breaks. Maybe there's a way to provide the certificate store for the individual packages (no idea, not sure there even is a certificate db on a Synology). The other solution is on the software's side: either turn off validation or include the root certificates as part of their software (which, in turn, we package)

**Comment by Diaoul** [comment]
OK I didn't get that DSM didn't provide the certificates... So maybe we need to provide our own certificates like you say. I've often see [Mozilla's](https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/) certificates used.

**Comment by Dr-Bean** [comment]
Sounds reasonable to me. There's probably a second part to the problem though, caused by self-signed certificates (and that, I believe, will fall to the package maintainers, because we can't fix that)

This sentence in the PEP might be helpful in solving the issue for embedded platforms like ours:
>OpenSSL also has a pair of environment variables, SSL_CERT_DIR and SSL_CERT_FILE which can be used to point Python at a different certificate database.

If we include the Mozilla certs, along with those vars, in the package, maybe that would fix things.

**Comment by Eldinnie** [comment]
At this moment Sickbeard has merged https://github.com/midgetspy/Sick-Beard/pull/912 in their development branch wich at least fixes the problem for sickbeard. Is it possible to distribute the development branch to the synocommunity?

**Comment by dakhdakh** [comment]
If it helps in anyway, there are a few threads in the SABnzb forums about this issue, e.g.
http://forums.sabnzbd.org/viewtopic.php?f=2&t=18027

**Comment by Eldinnie** [comment]
also about the certificate problem, I found this on Sab-forums: https://forums.sabnzbd.org/viewtopic.php?t=18771#p99598 wich creates a symlink to the certificates, This is a fix on OpenBSD but it might just work? I don't dare fumble for myself, but any thoughts?

**Comment by dakhdakh** [comment]
and this:

http://forums.sabnzbd.org/viewtopic.php?f=2&t=18509

**Comment by Dr-Bean** [comment]
So Sickbeard chose to drop verification then. Well, that works. 
@Eldinnie We're not going to change the default branch of Sickbeard. Contact the maintainers, request if they can merge master with develop: they do that periodically. 
Alternatively, change to using the `sickbeard-custom` package, then you can choose which fork/branch you want to use.

As for the second message: if there _are_ root certificates on a Synology (not sure, haven't checked), that might work. Otherwise, see the comments Diaoul and myself made just before yours: we might need to add them in as part of a package.

**Comment by Eldinnie** [comment]
@Dr-Bean I will ask them to do so, but that still leaves the problem that without SSL-support users won't be able to upgrade without a package upgrade, since sb/sab won't be able to reach the github-servers.

For you second suggestion to switch to custom I'm running into trouble, I removed Sickbeard and rebooted my NAS. Then tried to install the custom, but it gives me an error port 8083 is in use. This is true, because I run couchpotato on that port. Sickbeards default port is 8081, and this should be the check in the custom-build, not 8083

**Comment by Dr-Bean** [comment]
@Eldinnie Are you certain that Sickbeard won't be able to upgrade itself? Maybe a source on that?
As for your second problem, I disagree. The check in the sickbeard-custom package is fine as is, otherwise you can't install the sickbeard-custom package next to the sickbeard package... As for the port being in use: that's on you. Don't change the ports your applications are running on, it's near impossible for us to be able to provide support if you manually edit packages.

**Comment by Eldinnie** [comment]
@Dr-Bean You're right, I changed ports a bit and installing fine now.
Check this post on sb-forum: http://sickbeard.com/forums/viewtopic.php?f=4&t=9786
It shows a log where SB is unable to reach github due to SSL

**Comment by Diaoul** [comment]
This is because Synology doesn't provide certificates in a default location. This will be solved by a simple Python update when we know which fix to apply:
* locate the directory where DSM stores certificates
* add our own certificates

**Comment by Dr-Bean** [comment]
`/etc/ssl/certs?`

**Comment by dakhdakh** [comment]
There are also some certs in /usr/share/ca-certificates/mozilla/

**Comment by Dr-Bean** [comment]
This might just work as a quick fix: `ln -s /etc/ssl/certs/ca-certificates.crt /usr/local/python/cert.pem`
Note: at your own risk. I tested with Sickbeard, but I don't have an infrastructure available for proper testing.

**Comment by dakhdakh** [comment]
Thanks - tested working using SABnzb on my 1812+ running DSM 5.1 5022 update 4, Python 2.7.9, and SABnzb 0.7.20-13
Much appreciated.

**Comment by Eldinnie** [comment]
Tested on DS212+ running DSM 5.2-5532 Update 1 python 2.7.9 and sabNZB
0.7.20-13 also works.
thanks for this quick fix


Op zo 22 mrt. 2015 om 21:50 schreef dakhdakh <notifications@github.com>:

**Comment by Diaoul** [comment]
Wow that was fast. Good job.
If that's all it takes we can do that in the install script, right @Dr-Bean?

**Comment by Dr-Bean** [comment]
Yep, fine with me, I don't feel like figuring out if there's a more sensible solution today ;) 
I assume we could set OpenSSL's `openssl_cafile` var directly to that path, but meh, I don't think that's necessary right now. Will you handle the package update?

**Comment by Diaoul** [comment]
I'll compile during the night and publish tomorrow.

**Comment by Diaoul** [comment]
3a7d561a69b4caaaa6bb95030c898c516ce10f67 should fix it. Compiling now

**Comment by butcha** [comment]
I added the symlink, and that does help somewhat..
But I am still getting errors in sabnzbd when it tries to run the autoProcessTV.cfg for sickbeard:

Opening URL: https://localhost:1338/home/postprocess/processEpisode?nzbName=DOWNLOAD-NAME.nzb&quiet=1&dir=%2Fvolume1%2FVideo%2Fsabnzbd%2Fcomplete%2Fsickbeard%2FDOWNLOAD-NAME
Unable to open URL: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>

**Comment by Dr-Bean** [comment]
Is the certificate used for `https://localhost:1338` valid, or not? If not, there's your problem. As I said in a previous comment, we can't solve the issue for self-signed certificates: that's up to the software maintainers.

**Comment by butcha** [comment]
@Dr-Bean can you actually buy a valid cert for localhost? I add my own cert yes, and it is a valid cert (but not for localhost) for the actual address of my machine. But since sickbeard and sabnzbd are running on the same machine they connect through localhost... I guess i just have to change my setup a little to work around this instead. :)

**Comment by Dr-Bean** [comment]
Correct, you can't buy those :) There are several ways to handle that scenario, but all of those are rather off topic for this issue (e.g. don't use localhost to connect, use a DNS name for all traffic, don't use HTTPS for internal traffic, set up a local CA and probably a couple others)

**Comment by Diaoul** [comment]
I activated the builds on the server, you should have the update available in approx 10 minutes. Let me know if that fixes the issue.

**Comment by dakhdakh** [comment]
Thank you - great work.

**Comment by cuverysoon** [comment]
I dont know if I understood the conversation correctly, you did an update for Sickbeard solving the SSL problem? My Synology doesnt show a new Version. it still shows 20140528-5. Cause I have the same ssl problem.

**Comment by Dr-Bean** [comment]
No, Sickbeard can update itself, so we don't need to release a new package version. 
The maintainers have had a fix in their development branch since January, but they have not released it to their master branch yet (you'll have to ask them why not, because I don't know). See https://github.com/SynoCommunity/spksrc/issues/1600#issuecomment-85590085.

**Comment by Eldinnie** [comment]
@cuverysoon After the python upgrade sickbeard should be able to update itself, but this will also solve the problem with any other issues concerning SSL (as far as i;ve tested)

**Comment by cuverysoon** [comment]
@Eldinnie 
hmmm, my synology is up to date with all packages... but i am getting the mentionend errors, meaning I have to wait for the update to come.... ?
I also entered this just now: ln -s /etc/ssl/certs/ca-certificates.crt /usr/local/python/cert.pem
but no chnage on my ds412+

**Comment by Puntoboy** [comment]
I am getting these errors, since the upgrade of Python even though I'm using a public SSL certificate from GlobalSign. It seems Sickbeard and Sabnzbd have a problem with the intermediate certificate. I have tried separate intermediate (for Sab) and a joined certificate (cat server.crt intermediate.crt > chain.crt) but Sickbeard and Sabnzbd don't seem to read the intermediate. Couch potato on the other hand is reading it and correctly presenting this external (checked with SSL shopper). I have tried the above quick fix just now so just waiting to see if Sab and SB talk to each other once another episode downloads. But it's still strange they don't seem to like the intermediate chain.

**Comment by Diaoul** [comment]
There is no need to secure a `localhost` TCP connection, use http instead.
Python 2.7.9 and your application maintainers are to blame, not SynoCommunity or any package.

**Comment by Puntoboy** [comment]
The problem with SB and CP is that when you enable HTTPS it's HTTPS only. With Sab I believe you can fill connect using HTTP with HTTPS enabled on a separate port. 

I wasn't suggesting it was the SynoCommunity or Packages fault, I'm just here as I'm hoping someone can help me :(

**Comment by Dr-Bean** [comment]
Fyi, the fix mentioned previously is part of the Python 2.7.9-13 package, no need to enter it manually if you have that version of the package installed.

Apart from that, @Puntoboy: how did you establish that the intermediate certificate is the issue? That would seem unlikely (although it's possible, I don't know how often the certificate store is updated by Synology, maybe a new intermediate was issued)
You are using the domain name on the certificate to connect between SB/CP and SAB, not `localhost` or 0.0.0.0, right?

**Comment by Puntoboy** [comment]
I know the Intermediate isn't being sent as on SSL Shopper's SSL Cert check page I get told it isn't. Whereas for the Synology and Couchpotato address it's fine. I'm using the same certificates for each service but they are on different ports (I only have a single external IP). It's just Sab and SB that throw that error.

**Comment by Diaoul** [comment]
If you want HTTPS remote access to your services I suggest you use a reverse proxy like HAProxy. It will handle the SSL part for you and forward the requests to your local backeds (CouchPotato, SickBeard, etc.)
From a security pov I think it's a better approach too.

**Comment by Gremlyn** [comment]
So I just got around to updating and ran into this issue. I'm in a similar situation as those that run localhost https, but have an outward facing, properly signed cert for my outside accessible URL. I tried switching over to that URL expecting it to fix the problem, yet it did not. The cert is definitely in place and current, as I get no issues accessing the URL via the browser.

**Comment by gitsf** [comment]
Did something else cause it to break again?
I had this problem a few months ago when it first surfaced and it was working fine after creating the symlink.
Now I have just recently installed a bunch of synology package updates(dont remember what they all were(not sab or SB)) along with DSM 5.2-5565
I am back to getting the following error when SAB tries to call Sickbeard for postprocessing.
Unable to open URL: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
If I copy the url and open in a browser it works perfectly.

I have tried deleting the symlink and re-creating it. I am pretty sure I have the latest versions on Sickbeard & Sabnzbd.
Sickbeard: 20140528-5 (alpha (master) -- source : 31ceaf1b5cab1884a280fe3f4609bdc3b1fb3121)
Sabnzbd: 0.7.20-13
