### ISSUE TITLE
debian chroot package installs i386 not x86_64 on bromolow

### ISSUE THREAD

**Issue by sundalon** [SynoCommunity/spksrc#2250]
Hi there,

just did a fresh install of debian chroot on my DS3615xs running DSM 5.2-5644 Update 5.
Unfortunately the package as of version 8.1-6 installs debian i386 not x86_64.

```
root@sundalon:~# /var/packages/debian-chroot/scripts/start-stop-status start
Starting Debian Chroot ...
root@sundalon:~# /var/packages/debian-chroot/scripts/start-stop-status status
Debian Chroot is running
root@sundalon:~# /var/packages/debian-chroot/scripts/start-stop-status chroot
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
root@sundalon:/# uname -a
Linux sundalon 3.10.35 #1 SMP Tue Feb 2 17:44:24 CET 2016 x86_64 GNU/Linux
root@sundalon:/# dpkg --print-architecture
i386
```

What am I missing?

Cheers,

sundalon

**Comment by Dr-Bean** [comment]
That's because it's hardcoded to use i386 for all x86* arches: https://github.com/SynoCommunity/spksrc/blob/master/spk/debian-chroot/Makefile#L37. 
Presumably we could change it to `amd64` for x86_64 arches. We'd need to split off evansport in its own `ifeq`.

**Comment by sundalon** [comment]
That would be great.

Cheers,
sundalon

**Comment by Dr-Bean** [comment]
Done with 59ee0672a9547c3e8d108e4e8d0c9597fbff77f3. Debian-chroot 8.4-7 has been published on the repository.
Note that a reinstall of the package is needed if you want to switch, an upgrade won't do.

**Comment by sundalon** [comment]
Thanks, after a reinstall everything's working perfectly. 

Cheers, 
sundalon

On April 13, 2016 11:19:58 AM GMT+02:00, Dr-Bean <notifications@github.com> wrote:
>Done with 59ee0672a9547c3e8d108e4e8d0c9597fbff77f3. Debian-chroot 8.4-7
>has been published on the repository.
>Note that a reinstall of the package is needed if you want to switch,
>an upgrade won't do.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SynoCommunity/spksrc/issues/2250#issuecomment-209327277

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by r1sknt** [comment]
i have just tried the new update on the DSM6 but the problem of freezing UI still exists

**Comment by elRadix** [comment]
will this be fixed since the toolchain is out now ?
