### ISSUE TITLE
Couch Potato "Failed to run the package Service" DS214se

### ISSUE THREAD

**Issue by iversen666** [SynoCommunity/spksrc#2772]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_couchpotato custom
_Package Version:_20140604-4

_NAS Model:_Synology DS214se
_NAS Architecture:_?
_DSM version:_DSM 6.1.1-15101 Update 4

### Expected behavior
it should be running?

### Actual behavior
comes with the error Failed to run the package service
### Steps to reproduce
_1._go to package center | installed | couchpotato custom | Action | Run
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
there is no log available.

Follow the install instructions from here; https://www.crisi.ch/couchpotato-on-synology-nas/
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by melovedownvotes** [comment]
Same thing happens with sabnzbd and couchpotato with me.

**Comment by iversen666** [comment]
got the isue solved by a restart ^^

**Comment by ymartin59** [comment]
OK right. So please close this issue

**Comment by melovedownvotes** [comment]
This issue did not resolve for me with a NAS restart. I have the same DSM version and tried the non custom package which is version 20141013-6 of couchpotato with same issue as well.

**Comment by ilmtr** [comment]
Same error message here.

**Comment by Safihre** [comment]
Test packages for DSM6.1 and various architectures are available here #3138. They also include a new way of handling permissions.
We hope to publish the packages to the official repo soon and appreciate all testing and reports on the functioning of these packages.
