### ISSUE TITLE
dnscrypt-proxy - unable to Start Packages

### ISSUE THREAD

**Issue by Moonshinelunacy** [SynoCommunity/spksrc#3468]
Hello,

I am running DSM 6 on a DS918+ with Apollo Lake architecture. When installing new packages, the URL to actually run the package does not appear in the package center window. I have tried uninstalling and reinstalling the packages, and the problem persists across multiple packages.  Is there a way to find the URL's in another location?

**Comment by Moonshinelunacy** [comment]
Just double checked that permissions are all set to allow as they should. Additionally, I am logged in as the only account

**Comment by s1mwest** [comment]
I have similar issue:  "Failed to run the package service" after install DNScrypt-proxy and each time I attempt to run it from package ceter.  When I open the app, I see the following in the app window "fork/exc /user/syno/synoman/webman/login.cgi: permission denied"
DSM 6.1 Armada375 logged in as admin/only account
dnscrypt-proxy_armada375-6.1_2.0.16-0.spk

**Comment by BenjV** [comment]
Dat DNScrypt is een beta package en ik heb er even naar gekeken maar dit package kan helemaal nooit draaien op DSM.
Alle scripts om het te installeren en te kunnen starten en stoppen zijn leeg.

**Comment by s1mwest** [comment]
Are they both beta?
I used this one:  https://github.com/publicarray/spksrc/releases but there's no mention of it being beta - although I am a GitHub newbie and not very clued up (can you tell?)

The one at https://synocommunity.com/packages (dnscrypt.v1.f5004[armada375].spk) shows as beta - whilst this installed, there is no interface to work with to configure it.

Really appreciate the efforts by those who create these - really hope something final available

**Comment by ymartin59** [comment]
Publishment of dnscrypt-proxy is in progress: #3479

**Comment by publicarray** [comment]
Hi, sorry I'm late to the party. Yea I have't been able to test the package on the DSM until today. Thanks to Xpenology I can now run DSM in Virtualbox. And yea please @ me or send issues to the relevant gitub repo so I get notified.

I think the problem is that the generic script for the DSM `chown`'s all files:
![](https://user-images.githubusercontent.com/5497998/47199172-feae9700-d3bb-11e8-9fba-0aa44606fe18.png)

I'll have to chown the cgi script somehow

**Comment by publicarray** [comment]
The beta flag for SynoCommunity packages can be found in the makefiles here: https://github.com/SynoCommunity/spksrc/blob/e914a32600e65f80131ae09913f1b6f6a2dd8b13/spk/dnscrypt-proxy/Makefile#L17

Or on the webpage with the red beta flag https://synocommunity.com/packages

As for being in beta, I've been running dnscrypt-proxy successfully on my RT2600ac router for months without major issues. But I'm biased 😃

**Comment by publicarray** [comment]
@s1mwest I've pushed a new release in my fork: https://github.com/publicarray/spksrc/releases/tag/dnscrypt-proxy-2.0.17_1

Please let me know if it work for you.

**Comment by publicarray** [comment]
@s1mwest Thanks for testing 👍

Looks like a syntax error in the configuration from `dnscrypt-proxy` side, My package runs `dnscrypt-proxy -check` on every file save. Can you run `dnscrypt-proxy -check -config /path/to/config/file` on your laptop with the same configuration? Are all the clocking rules in the `clocking-rules.txt` file and not the `dnscrypt-proxy.toml` file?

**Comment by s1mwest** [comment]
:/ not sure how to run that on my laptop (excuse my incompetence!) and I've only tried adding 1 rule in the .toml file so far (only need 2) - I assumed the .toml file would work because it successfully saved my change of listen_addresses port.  Absolutely love this creation; it's way more than a pleasure to test :)

**Comment by publicarray** [comment]
@s1mwest No worries 

so If I understand correctly all you need to do is uncomment line 248 in the `toml` file and add your rules in the `cloaking-rules.txt` file (see image).

```toml
###############################
#        Cloaking rules       #
###############################

## Cloaking returns a predefined address for a specific name.
## In addition to acting as a HOSTS file, it can also return the IP address
## of a different name. It will also do CNAME flattening.
##
## Example map entries (one entry per line)
## example.com     10.1.1.1
## www.google.com  forcesafesearch.google.com

cloaking_rules = 'cloaking-rules.txt'
```

![screen shot](https://user-images.githubusercontent.com/5497998/47245074-95726680-d443-11e8-84b1-ecdf8555fa27.png)

**Comment by s1mwest** [comment]
Hey thanks! Worked a treat.  Had to stop/start the package for the new additions to work.  Maybe I was just being impatient lol  Anyway, thanks for all your help publicarray - think I've digressed this thread enough but I now have a working DNS Crypt server on my Synology NAS - and so will other peeps :D Cheers buddy

**Comment by publicarray** [comment]
@s1mwest should be fixed in the new release: https://github.com/publicarray/spksrc/releases

**Comment by s1mwest** [comment]
Thanks!  Still getting same behaviour though;  blacklist.txt file is working when I test a manually added domain i.e. it saves the txt file and domain is successfully blocked after package restarted.  Generating the blacklist overwrites the blacklist.txt file with empty contents for me still :(  It takes about 2 seconds to show 'file saved successfully' (is that too quick?)  I'm using default settings in 'domains-blacklist.conf' file and the line blacklist_file = 'blacklist.txt' is uncommented in my .toml file . The only time I'm seeing any entries in blacklist.txt is after package uninstall/reinstall.  Hope this info helps - happy to continue testing if you're happy to continue fixing :D
