### ISSUE TITLE
[Lidarr] Not valid DSM path

### ISSUE THREAD

**Issue by mnervik** [SynoCommunity/spksrc#3702]
### Setup
Lidarr
0.6.1.830

DS1517+
Avoton (x64)
6.2.1-23824

### Expected behavior
No error and Lidarr should connect to Synology Download Station

### Actual behavior
- "Local download client ds1517 places downloads in but this is not a valid DSM path. Review your download client settings." error message in the health column
- Testing the download client gives no error
- Manually setting the shared folder in the "download client" settings (in Lidarr) gives the same error in health column
- Using transmission instead of download stations works...

**Comment by BenjV** [comment]
You also have to set that same location you set in Lidarr in DownloadStation so they use the same location.

**Comment by ta264** [comment]
This is was a bug in lidarr fixed in 0.6.2

**Comment by ymartin59** [comment]
@m4tt075 Hello. Anything to do about this Lidarr update?

**Comment by mnervik** [comment]
Just wanted to make an update to this issue.

- The health message is no longer displayed after updating to 0.6.2.883
- Trying to download is still not possible, currently gives another error message in the queue
![JPG](https://user-images.githubusercontent.com/15329600/58513694-5c039580-81a0-11e9-8b6b-b800817e51f7.jpg)

**Comment by mnervik** [comment]
Did this ever get solved. I'm still getting this error (Version: 0.7.1.1381)

- Testing the download-client gives no error
- Trying to download a release gives the error `Pending - Download client is unavailable`
