### ISSUE TITLE
ZNC fails to start after update to 1.8.1-15

### ISSUE THREAD

**Issue by stephenbond** [SynoCommunity/spksrc#4279]
### Setup
ZNC
1.8.1-15

DS215j
MARVELL Armada 375 88F6720
DSM 6.2.3-25426 Update 2

### Expected behaviour
Service starts

### Actual behaviour
It doesn't start

### Steps to reproduce
Update from 1.7.5-13

#### Other logs
2020-11-06T13:59:24+00:00 NAS synoscgi_SYNO.Core.Package.Control_1_start[15796]: servicecfg_internal_lib.c:22 Failed to start job [pkgctl-znc][0xD900 manager.cpp:204]
2020-11-06T13:59:24+00:00 NAS kernel: [3117889.194244] init: pkgctl-znc pre-start process (18457) terminated with status 1
2020-11-06T13:59:25+00:00 NAS synoscgi_SYNO.Core.Package.Control_1_start[15796]: pkgstartstop.cpp:371 Failed to start pkgctl-znc (err=-1) [0xD900 manager.cpp:204]
2020-11-06T14:11:06+00:00 NAS kernel: [  476.875776] init: pkgctl-znc pre-start process (17989) terminated with status 1

**Comment by urdh** [comment]
Having a similar issue on my RS217 (MARVELL Armada 385 88F6820, DSM 6.2.3-25426 Update 3).

`znc.log` says this:

```sh
$ more /volume1/@appstore/znc/var/znc.log
Mon Jan  4 11:23:29 CET 2021
Starting znc command env LD_LIBRARY_PATH=/var/packages/python3/target/lib /volume1/@appstore/znc/bin/znc -d /volume1/@appstore/znc/var
Certificate file exists. Starting...
/volume1/@appstore/znc/bin/znc: error while loading shared libraries: /var/packages/znc/target/lib/libicudata.so.67: internal error
```

**Comment by publicarray** [comment]
Can confirm it works on both dsm7 and dsm6 on x64:

```
seby@NAS:~$ cat /var/packages/znc/var/znc.log
Sun Jan 24 17:16:43 AEDT 2021
Starting znc command env LD_LIBRARY_PATH=/var/packages/python3/target/lib /volume1/@appstore/znc/bin/znc -d /volume1/@appdata/znc 
Generating initial certificate file
Writing Pem file [/volume1/@appdata/znc/znc.pem]... 
Certificate file created. Starting...
Checking for list of available modules... 
Opening config [/volume1/@appdata/znc/configs/znc.conf]... 
Loading global module [webadmin]... 
Binding to port [8250]... 
Binding to port [+8251]... 
Loading user [admin]
Forking into the background... [pid: 19324]
Writing pid file [/volume1/@appdata/znc/znc.pid]... 
ZNC 1.8.2 - https://znc.in

$ cat /var/packages/znc/target/var/znc.log 
Sun Jan 24 17:41:50 AEDT 2021
Starting znc command env LD_LIBRARY_PATH=/var/packages/python3/target/lib /volume1/@appstore/znc/bin/znc -d /volume1/@appstore/znc/var 
Generating initial certificate file
Writing Pem file [/volume1/@appstore/znc/var/znc.pem]... 
Certificate file created. Starting...
Checking for list of available modules... 
Opening config [/volume1/@appstore/znc/var/configs/znc.conf]... 
Loading global module [webadmin]... 
Binding to port [8250]... 
Binding to port [+8251]... 
Loading user [admin]
Forking into the background... [pid: 27874]
Writing pid file [/volume1/@appstore/znc/var/znc.pid]... 
ZNC 1.8.2 - https://znc.in
```

**Comment by hgy59** [comment]
fixed with #4393

**Comment by urdh** [comment]
Still seeing this issue on my RS217 with the 1.8.2-17 ZNC package.

**Comment by acesabe** [comment]
Same, DS216j , DSM 6.2.3-25426 Update 3, ZNC upgraded to 1.8.2-17 but fails to start:

```
Mon Feb  8 17:25:11 CET 2021
Starting znc command env LD_LIBRARY_PATH=/var/packages/python3/target/lib /volume1/@appstore/znc/bin/znc -d /volume1/@appstore/znc/var 
Certificate file exists. Starting...
/volume1/@appstore/znc/bin/znc: error while loading shared libraries: /var/packages/znc/target/lib/libicudata.so.68: internal error
```
Note: ZNC was not running before the upgrade to latest version, not sure since when as I rarely check irc these days but it may have already been broken? Can't find any old log entries to elaborate on this I'm afraid.

My suspicions point towards updated LetsEncrypt Certs but I have no way to prove or find out if this is pure conjecture or not! =D

**Comment by hgy59** [comment]
found this error elsewhere:
https://sourceforge.net/p/icu/mailman/message/36666855/
https://crux-arm.nu/bugs/index.php?do=details&task_id=76&opened=3&status%5B0%5D=
but no solution yet.

**Comment by smaarn** [comment]
(Surely stupid) question: does it work better with the `LD_LIBRARY_PATH` including the lib directory ?
E.g. from what I see the current script goes `env LD_LIBRARY_PATH=/var/packages/python3/target/lib ...`, shouldn't it be something such as `env LD_LIBRARY_PATH=/var/packages/python3/target/lib:/var/packages/znc/target/lib ...` ?

**Comment by urdh** [comment]
No luck, unfortunately:

```
Starting znc command env LD_LIBRARY_PATH=/var/packages/python3/target/lib:/volume1/@appstore/znc/lib /volume1/@appstore/znc/bin/znc -d /volume1/@appstore/znc/var
Certificate file exists. Starting...
/volume1/@appstore/znc/bin/znc: error while loading shared libraries: /var/packages/znc/target/lib/libicudata.so.68: internal error
```

With the 1.8.1-15 build I did some very cursory digging and from what I remember the ICU shared libraries were built for the wrong architecture. I haven't had the time to do any digging on 1.8.2-17, though.

**Comment by ymartin59** [comment]
It may be an issue from RPATH generation in .so files knowing there is a post-processing script "tuning" references in binary files in-place... "internal error" sounds really weird...

**Comment by stephenbond** [comment]
Is this fixed with, 1.8.2-17...i guess i could install and find out.

**Comment by urdh** [comment]
This is still an issue for me with DSM 7.0 and ZNC 1.8.2-18:

```
Thu Aug 19 21:45:53 CEST 2021
Begin service_prestart
Certificate file exists. Starting...
End service_prestart
Starting znc command env LD_LIBRARY_PATH=/var/packages/python38/target/lib /volume1/@appstore/znc/bin/znc -d /volume1/@appdata/znc 
/volume1/@appstore/znc/bin/znc: error while loading shared libraries: /var/packages/znc/target/lib/libicudata.so.68: internal error
znc is not running
```

**Comment by stephenbond** [comment]
Not just me then. This package should be removed from SynoCommunity, not worked for years
